-- CreateTable
CREATE TABLE "contexts" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "temporal" TEXT NOT NULL,
    "spatial" TEXT NOT NULL,
    "priority" TEXT NOT NULL,
    "relational" TEXT NOT NULL,
    "intentional" TEXT NOT NULL,
    "contextScore" REAL NOT NULL DEFAULT 50,
    "version" INTEGER NOT NULL DEFAULT 1,
    "lastUpdated" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "contexts_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "clusters" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "type" TEXT NOT NULL,
    "color" TEXT,
    "icon" TEXT,
    "centroid" TEXT,
    "cohesion" REAL NOT NULL DEFAULT 0,
    "size" INTEGER NOT NULL DEFAULT 0,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "clusters_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "actions" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "triggerId" TEXT NOT NULL,
    "triggerType" TEXT NOT NULL,
    "actionType" TEXT NOT NULL,
    "targetEntityId" TEXT NOT NULL,
    "targetEntityType" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "reasoning" TEXT NOT NULL,
    "confidence" REAL NOT NULL,
    "isAutomatic" BOOLEAN NOT NULL DEFAULT false,
    "requiresConfirmation" BOOLEAN NOT NULL DEFAULT true,
    "payload" TEXT NOT NULL,
    "state" TEXT NOT NULL DEFAULT 'PENDING',
    "userFeedback" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "executedAt" DATETIME,
    "expiresAt" DATETIME,
    CONSTRAINT "actions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "interaction_logs" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "entityId" TEXT,
    "entityType" TEXT,
    "duration" INTEGER NOT NULL,
    "contextSnapshot" TEXT,
    "metadata" TEXT,
    "timestamp" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "interaction_logs_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "patterns" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "sequence" TEXT NOT NULL,
    "frequency" INTEGER NOT NULL DEFAULT 1,
    "confidence" REAL NOT NULL DEFAULT 0,
    "typicalContext" TEXT,
    "lastOccurred" DATETIME NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "patterns_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "user_feedbacks" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "predictionId" TEXT,
    "predictionType" TEXT NOT NULL,
    "wasCorrect" BOOLEAN NOT NULL,
    "actualAction" TEXT,
    "actualOutcome" TEXT,
    "comment" TEXT,
    "timestamp" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "user_feedbacks_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "contexts_entityId_key" ON "contexts"("entityId");

-- CreateIndex
CREATE INDEX "contexts_userId_contextScore_idx" ON "contexts"("userId", "contextScore");

-- CreateIndex
CREATE INDEX "contexts_userId_entityType_idx" ON "contexts"("userId", "entityType");

-- CreateIndex
CREATE INDEX "contexts_entityId_idx" ON "contexts"("entityId");

-- CreateIndex
CREATE INDEX "clusters_userId_type_idx" ON "clusters"("userId", "type");

-- CreateIndex
CREATE INDEX "clusters_userId_autoGenerated_idx" ON "clusters"("userId", "autoGenerated");

-- CreateIndex
CREATE INDEX "actions_userId_state_createdAt_idx" ON "actions"("userId", "state", "createdAt");

-- CreateIndex
CREATE INDEX "actions_userId_targetEntityId_idx" ON "actions"("userId", "targetEntityId");

-- CreateIndex
CREATE INDEX "actions_state_expiresAt_idx" ON "actions"("state", "expiresAt");

-- CreateIndex
CREATE INDEX "interaction_logs_userId_timestamp_idx" ON "interaction_logs"("userId", "timestamp");

-- CreateIndex
CREATE INDEX "interaction_logs_userId_action_idx" ON "interaction_logs"("userId", "action");

-- CreateIndex
CREATE INDEX "interaction_logs_entityId_idx" ON "interaction_logs"("entityId");

-- CreateIndex
CREATE INDEX "patterns_userId_frequency_idx" ON "patterns"("userId", "frequency");

-- CreateIndex
CREATE INDEX "patterns_userId_lastOccurred_idx" ON "patterns"("userId", "lastOccurred");

-- CreateIndex
CREATE INDEX "user_feedbacks_userId_predictionType_idx" ON "user_feedbacks"("userId", "predictionType");

-- CreateIndex
CREATE INDEX "user_feedbacks_predictionId_idx" ON "user_feedbacks"("predictionId");
