// Constantes de la aplicación

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const ERROR_CODES = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  UNAUTHORIZED: 'UNAUTHORIZED',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_FORMAT: 'INVALID_FORMAT',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',

  // Business Logic
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  OPERATION_FAILED: 'OPERATION_FAILED',

  // External Services
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  MCP_EXECUTION_FAILED: 'MCP_EXECUTION_FAILED',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export const EVENT_TYPES = {
  MEDICAL: 'MEDICAL',
  MEETING: 'MEETING',
  PERSONAL: 'PERSONAL',
  WORK: 'WORK',
  BIRTHDAY: 'BIRTHDAY',
  APPOINTMENT: 'APPOINTMENT',
  SOCIAL: 'SOCIAL',
  EXERCISE: 'EXERCISE',
  SHOPPING: 'SHOPPING',
  TRAVEL: 'TRAVEL',
  OTHER: 'OTHER',
} as const;

export const CREATION_SOURCE = {
  VOICE: 'VOICE',
  MANUAL: 'MANUAL',
  IMPORT: 'IMPORT',
  MCP: 'MCP',
} as const;

export const REMINDER_CHANNEL = {
  PUSH: 'PUSH',
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  VOICE: 'VOICE',
} as const;

export const ALARM_SOUND = {
  DEFAULT: 'DEFAULT',
  MUSIC: 'MUSIC',
  VOICE: 'VOICE',
  GENTLE: 'GENTLE',
  NATURE: 'NATURE',
} as const;

export const MCP_TYPE = {
  PRECONFIGURED: 'PRECONFIGURED',
  DYNAMIC: 'DYNAMIC',
  USER_CREATED: 'USER_CREATED',
} as const;

export const MCP_CATEGORY = {
  COMMUNICATION: 'COMMUNICATION',
  LOCATION: 'LOCATION',
  WEB: 'WEB',
  MEDIA: 'MEDIA',
  PRODUCTIVITY: 'PRODUCTIVITY',
  WEATHER: 'WEATHER',
  FINANCE: 'FINANCE',
  SOCIAL: 'SOCIAL',
  OTHER: 'OTHER',
} as const;

export const MESSAGE_PLATFORM = {
  WHATSAPP: 'WHATSAPP',
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  TELEGRAM: 'TELEGRAM',
} as const;

export const MESSAGE_DIRECTION = {
  INCOMING: 'INCOMING',
  OUTGOING: 'OUTGOING',
} as const;

export const MESSAGE_STATUS = {
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  READ: 'READ',
  FAILED: 'FAILED',
} as const;

export const LOCATION_ACTION = {
  ARRIVAL: 'ARRIVAL',
  DEPARTURE: 'DEPARTURE',
  PROXIMITY: 'PROXIMITY',
  CHECK: 'CHECK',
} as const;

export const USER_FEEDBACK = {
  POSITIVE: 'POSITIVE',
  NEGATIVE: 'NEGATIVE',
  NEUTRAL: 'NEUTRAL',
} as const;

export const NLP_INTENTS = {
  CREATE_EVENT: 'CREATE_EVENT',
  QUERY_AGENDA: 'QUERY_AGENDA',
  MODIFY_EVENT: 'MODIFY_EVENT',
  DELETE_EVENT: 'DELETE_EVENT',
  SEND_MESSAGE: 'SEND_MESSAGE',
  READ_MESSAGES: 'READ_MESSAGES',
  GET_LOCATION_INFO: 'GET_LOCATION_INFO',
  CREATE_ALARM: 'CREATE_ALARM',
  GREETING: 'GREETING',
  SEARCH_WEB: 'SEARCH_WEB',
} as const;

export const RATE_LIMITS = {
  GENERAL: 100, // requests per 15 minutes
  AUTH: 10, // login attempts per 15 minutes
  MCP_EXECUTION: 30, // MCP executions per minute
} as const;

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 50,
  MAX_LIMIT: 100,
} as const;

export const DATE_FORMATS = {
  ISO: 'YYYY-MM-DDTHH:mm:ss.SSSZ',
  DATE_ONLY: 'YYYY-MM-DD',
  TIME_ONLY: 'HH:mm:ss',
  DISPLAY: 'DD/MM/YYYY HH:mm',
} as const;

export default {
  HTTP_STATUS,
  ERROR_CODES,
  EVENT_TYPES,
  CREATION_SOURCE,
  REMINDER_CHANNEL,
  ALARM_SOUND,
  MCP_TYPE,
  MCP_CATEGORY,
  MESSAGE_PLATFORM,
  MESSAGE_DIRECTION,
  MESSAGE_STATUS,
  LOCATION_ACTION,
  USER_FEEDBACK,
  NLP_INTENTS,
  RATE_LIMITS,
  PAGINATION,
  DATE_FORMATS,
};
